spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${STUDYMATE_DB_URL:jdbc:mysql://localhost:3306/studymate?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${STUDYMATE_DB_USERNAME:root}
    password: ${STUDYMATE_DB_PASSWORD:1234}

logging:
  level:
    com.studymate: debug
